<?php

use Illuminate\Database\Seeder;

class seedPermissions extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        
        DB::table('permissions')->insert([
            ["name" => "App\Http\Controllers\StaticPageController@home"],
            ["name" => "App\Http\Controllers\StaticPageController@contact"],
            ["name" => "App\Http\Controllers\StaticPageController@postContact"],
            ["name" => "App\Http\Controllers\StaticPageController@page"],
            ["name" => "App\Http\Controllers\AccessController@social"],
            ["name" => "App\Http\Controllers\AccessController@login"],
            ["name" => "App\Http\Controllers\AccessController@postLogin"],
            ["name" => "App\Http\Controllers\AccessController@logout"],
            ["name" => "App\Http\Controllers\AccessController@forgotPassword"],
            ["name" => "App\Http\Controllers\AccessController@postForgotPassword"],
            ["name" => "App\Http\Controllers\AccessController@signup"],
            ["name" => "App\Http\Controllers\AccessController@postSignup"],
            ["name" => "App\Http\Controllers\Dashboard@index"],
            ["name" => "App\Http\Controllers\Roles@permission"],
            ["name" => "App\Http\Controllers\Roles@postPermission"],
            ["name" => "App\Http\Controllers\Roles@index"],
            ["name" => "App\Http\Controllers\Roles@create"],
            ["name" => "App\Http\Controllers\Roles@store"],
            ["name" => "App\Http\Controllers\Roles@show"],
            ["name" => "App\Http\Controllers\Roles@edit"],
            ["name" => "App\Http\Controllers\Roles@update"],
            ["name" => "App\Http\Controllers\Roles@destroy"],
            ["name" => "App\Http\Controllers\Navs@index"],
            ["name" => "App\Http\Controllers\Navs@create"],
            ["name" => "App\Http\Controllers\Navs@store"],
            ["name" => "App\Http\Controllers\Navs@update"],
            ["name" => "App\Http\Controllers\Socials@searchIndex"],
            ["name" => "App\Http\Controllers\Socials@index"],
            ["name" => "App\Http\Controllers\Socials@create"],
            ["name" => "App\Http\Controllers\Socials@store"],
            ["name" => "App\Http\Controllers\Socials@show"],
            ["name" => "App\Http\Controllers\Socials@edit"],
            ["name" => "App\Http\Controllers\Socials@update"],
            ["name" => "App\Http\Controllers\Socials@destroy"],
            ["name" => "App\Http\Controllers\Users@index"],
            ["name" => "App\Http\Controllers\Users@create"],
            ["name" => "App\Http\Controllers\Users@store"],
            ["name" => "App\Http\Controllers\Users@show"],
            ["name" => "App\Http\Controllers\Users@edit"],
            ["name" => "App\Http\Controllers\Users@update"],
            ["name" => "App\Http\Controllers\Users@destroy"],
            ["name" => "App\Http\Controllers\AccessController@changePassword"],
            ["name" => "App\Http\Controllers\AccessController@postChangePassword"],
            ["name" => "App\Http\Controllers\Settings@show"],
            ["name" => "App\Http\Controllers\Settings@edit"],
            ["name" => "App\Http\Controllers\Settings@update"],
            ["name" => "App\Http\Controllers\Pages@searchIndex"],
            ["name" => "App\Http\Controllers\Pages@index"],
            ["name" => "App\Http\Controllers\Pages@create"],
            ["name" => "App\Http\Controllers\Pages@store"],
            ["name" => "App\Http\Controllers\Pages@show"],
            ["name" => "App\Http\Controllers\Pages@edit"],
            ["name" => "App\Http\Controllers\Pages@update"],
            ["name" => "App\Http\Controllers\Pages@destroy"],
            ["name" => "App\Http\Controllers\Currencies@searchIndex"],
            ["name" => "App\Http\Controllers\Currencies@index"],
            ["name" => "App\Http\Controllers\Currencies@create"],
            ["name" => "App\Http\Controllers\Currencies@store"],
            ["name" => "App\Http\Controllers\Currencies@show"],
            ["name" => "App\Http\Controllers\Currencies@edit"],
            ["name" => "App\Http\Controllers\Currencies@update"],
            ["name" => "App\Http\Controllers\Currencies@destroy"],
            ["name" => "App\Http\Controllers\Gateways@searchIndex"],
            ["name" => "App\Http\Controllers\Gateways@index"],
            ["name" => "App\Http\Controllers\Gateways@create"],
            ["name" => "App\Http\Controllers\Gateways@store"],
            ["name" => "App\Http\Controllers\Gateways@show"],
            ["name" => "App\Http\Controllers\Gateways@edit"],
            ["name" => "App\Http\Controllers\Gateways@update"],
            ["name" => "App\Http\Controllers\Gateways@destroy"],
            ["name" => "App\Http\Controllers\Shippings@searchIndex"],
            ["name" => "App\Http\Controllers\Shippings@index"],
            ["name" => "App\Http\Controllers\Shippings@create"],
            ["name" => "App\Http\Controllers\Shippings@store"],
            ["name" => "App\Http\Controllers\Shippings@show"],
            ["name" => "App\Http\Controllers\Shippings@edit"],
            ["name" => "App\Http\Controllers\Shippings@update"],
            ["name" => "App\Http\Controllers\Shippings@destroy"],
            ["name" => "App\Http\Controllers\MyProfile@show"],
            ["name" => "App\Http\Controllers\MyProfile@update"],
            ["name" => "App\Http\Controllers\MyProfile@edit"],
            ["name" => "App\Http\Controllers\MyProfile@changePassword"],
            ["name" => "App\Http\Controllers\MyProfile@updatePassword"],
            ["name" => "App\Http\Controllers\Permissions@searchIndex"],
            ["name" => "App\Http\Controllers\Permissions@autoUpdate"],
            ["name" => "App\Http\Controllers\Permissions@index"],
            ["name" => "App\Http\Controllers\Permissions@create"],
            ["name" => "App\Http\Controllers\Permissions@store"],
            ["name" => "App\Http\Controllers\Permissions@show"],
            ["name" => "App\Http\Controllers\Permissions@edit"],
            ["name" => "App\Http\Controllers\Permissions@update"],
            ["name" => "App\Http\Controllers\Permissions@destroy"],
        ]);
        
    }
}
