<?php

use Illuminate\Database\Seeder;

class skillChildsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        
        DB::table('skillchilds')->insert([
            ['name'=> 'AngularJS',              'skillitem_id'=> '1', 'language_id'=> '1'],
            ['name'=> 'Backbone.js',            'skillitem_id'=> '1', 'language_id'=> '1'],
            ['name'=> 'Cappuccino',             'skillitem_id'=> '1', 'language_id'=> '1'],
            ['name'=> 'Chaplin.js',             'skillitem_id'=> '1', 'language_id'=> '1'],
            ['name'=> 'Echo',                   'skillitem_id'=> '1', 'language_id'=> '1'],
            ['name'=> 'Ember.js',               'skillitem_id'=> '1', 'language_id'=> '1'],
            ['name'=> 'Enyo',                   'skillitem_id'=> '1', 'language_id'=> '1'],
            ['name'=> 'Ext JS',                 'skillitem_id'=> '1', 'language_id'=> '1'],
            ['name'=> 'Google Web Toolkit',     'skillitem_id'=> '1', 'language_id'=> '1'],
            ['name'=> 'JavaScriptMVC',          'skillitem_id'=> '1', 'language_id'=> '1'],
            ['name'=> 'Knockout',               'skillitem_id'=> '1', 'language_id'=> '1'],
            ['name'=> 'Meteor',                 'skillitem_id'=> '1', 'language_id'=> '1'],
            ['name'=> 'Mojito',                 'skillitem_id'=> '1', 'language_id'=> '1'],
            ['name'=> 'MooTools',               'skillitem_id'=> '1', 'language_id'=> '1'],
            ['name'=> 'Prototype JavaScript Framework', 'skillitem_id'=> '1', 'language_id'=> '1'],
            ['name'=> 'React.js',               'skillitem_id'=> '1', 'language_id'=> '1'],
            ['name'=> 'Rialto Toolkit',         'skillitem_id'=> '1', 'language_id'=> '1'],
            ['name'=> 'SproutCore',             'skillitem_id'=> '1', 'language_id'=> '1'],
            ['name'=> 'Wakanda Framework',      'skillitem_id'=> '1', 'language_id'=> '1'],
            ['name'=> 'Rails',                  'skillitem_id'=> '2', 'language_id'=> '1'],
            ['name'=> 'Spring MVC',             'skillitem_id'=> '3', 'language_id'=> '1'],
            ['name'=> 'Struts 1.x',             'skillitem_id'=> '3', 'language_id'=> '1'],
            ['name'=> 'Apache Axis',            'skillitem_id'=> '3', 'language_id'=> '1'],
            ['name'=> 'Apache Xerces',          'skillitem_id'=> '3', 'language_id'=> '1'],
            ['name'=> 'Hibernate',              'skillitem_id'=> '3', 'language_id'=> '1'],
            ['name'=> 'JDOM',                   'skillitem_id'=> '3', 'language_id'=> '1'],
            ['name'=> 'Java Applet',            'skillitem_id'=> '3', 'language_id'=> '1'],
            ['name'=> 'Apache Velocity',        'skillitem_id'=> '3', 'language_id'=> '1'],
            ['name'=> 'Apache ORO',             'skillitem_id'=> '3', 'language_id'=> '1'],
            ['name'=> 'JAX-WS',                 'skillitem_id'=> '3', 'language_id'=> '1'],
            ['name'=> 'Phalcon',                'skillitem_id'=> '4', 'language_id'=> '1'],
            ['name'=> 'Slim',                   'skillitem_id'=> '4', 'language_id'=> '1'],
            ['name'=> 'Kohana',                 'skillitem_id'=> '4', 'language_id'=> '1'],
            ['name'=> 'CSS ',     'skillitem_id'=> '45', 'language_id'=> '1'],
            ['name'=> 'D3.js  ', 'skillitem_id'=> '45', 'language_id'=> '1'],
            ['name'=> 'Dust.js  ', 'skillitem_id'=> '45', 'language_id'=> '1'],
            ['name'=> 'EaselJS ', 'skillitem_id'=> '45', 'language_id'=> '1'],
            ['name'=> 'Edge Animate  ', 'skillitem_id'=> '45', 'language_id'=> '1'],
            ['name'=> 'Ember.js  ', 'skillitem_id'=> '45', 'language_id'=> '1'],
            ['name'=> 'Express.js  ', 'skillitem_id'=> '45', 'language_id'=> '1'],
            ['name'=> 'Flex  ', 'skillitem_id'=> '45', 'language_id'=> '1'],
            ['name'=> 'Grunt.js  ', 'skillitem_id'=> '45', 'language_id'=> '1'],
            ['name'=> 'Handlebars.js  ', 'skillitem_id'=> '45', 'language_id'=> '1'],
            ['name'=> 'HTML  ', 'skillitem_id'=> '45', 'language_id'=> '1'],
            ['name'=> 'Java  ', 'skillitem_id'=> '45', 'language_id'=> '1'],
            ['name'=> 'JavaScript ', 'skillitem_id'=> '45', 'language_id'=> '1'],
            ['name'=> 'Jekyll', 'skillitem_id'=> '45', 'language_id'=> '1'],
            ['name'=> 'jQuery  ', 'skillitem_id'=> '45', 'language_id'=> '1'],
            ['name'=> 'jQuery Mobile ', 'skillitem_id'=> '45', 'language_id'=> '1'],
            ['name'=> 'JSON  ', 'skillitem_id'=> '45', 'language_id'=> '1'],
            ['name'=> 'LESS  ', 'skillitem_id'=> '45', 'language_id'=> '1'],
            ['name'=> 'Muse ', 'skillitem_id'=> '45', 'language_id'=> '1'],
            ['name'=> 'Mustache.js  ', 'skillitem_id'=> '45', 'language_id'=> '1'],
            
            ['name'=> 'MySQL  ', 'skillitem_id'=> '45', 'language_id'=> '1'],
            ['name'=> 'Node.js  ', 'skillitem_id'=> '45', 'language_id'=> '1'],
            ['name'=> 'Perl  ', 'skillitem_id'=> '45', 'language_id'=> '1'],
            ['name'=> 'Phaser  ', 'skillitem_id'=> '45', 'language_id'=> '1'],
            ['name'=> 'PHP  ', 'skillitem_id'=> '45', 'language_id'=> '1'],
            ['name'=> 'PostgreSQL ', 'skillitem_id'=> '45', 'language_id'=> '1'],
            ['name'=> 'Prototype ', 'skillitem_id'=> '45', 'language_id'=> '1'],
            ['name'=> 'Python ', 'skillitem_id'=> '45', 'language_id'=> '1'],
            ['name'=> 'Ratchet', 'skillitem_id'=> '45', 'language_id'=> '1'],
            ['name'=> 'React.js ', 'skillitem_id'=> '45', 'language_id'=> '1'],
            ['name'=> 'reveal.js ', 'skillitem_id'=> '45', 'language_id'=> '1'],
            ['name'=> 'Ruby ', 'skillitem_id'=> '45', 'language_id'=> '1'],
            ['name'=> 'Ruby on Rails', 'skillitem_id'=> '45', 'language_id'=> '1'],
            ['name'=> 'Sass', 'skillitem_id'=> '45', 'language_id'=> '1'],
            ['name'=> 'Starling  ', 'skillitem_id'=> '45', 'language_id'=> '1'],
            ['name'=> 'Underscore.js  ', 'skillitem_id'=> '45', 'language_id'=> '1'],
            ['name'=> 'XHTML ', 'skillitem_id'=> '45', 'language_id'=> '1'],
            ['name'=> 'XML  ', 'skillitem_id'=> '45', 'language_id'=> '1'],
            ['name'=> 'YAML ', 'skillitem_id'=> '45', 'language_id'=> '1'],
            ['name'=> 'C# ', 'skillitem_id'=> '45', 'language_id'=> '1'],
            ['name'=> 'littleBits', 'skillitem_id'=> '46', 'language_id'=> '1'],
            ['name'=> 'littleBits', 'skillitem_id'=> '47', 'language_id'=> '1'],
            ['name'=> 'Acrobat ', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'Adobe', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'After Effects ', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'Axure ', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'Azure ', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'Cake Software', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'CGI ', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'Cinemagraph Pro ', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'ColdFusion ', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'Creative Cloud ', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'Dreamweaver ', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'Drupal ', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'Fireworks ', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'Flash ', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'Flash Builder ', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'Flash Catalyst ', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'Flash Professional ', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'Flex Builder ', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'Illustrator ', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'ImageReady ', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'InDesign ', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'Microsoft ', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'Papervision 3D ', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'PhoneGap ', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'Photoshop', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'phpMyAdmin ', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'Quark', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'Silverlight ', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'SQLite ', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'Titanium ', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'Visual Studio Express', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'ActionScript ', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'Ajax ', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'AngularJS', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'Backbone.js ', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'Bootstrap ', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'CreateJS', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'CoffeeScript ', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'CSS', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'D3.js', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'Dust.js ', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'EaselJS ', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'Edge Animate ', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'Ember.js ', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'Express.js', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'Flex ', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'Grunt.js ', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'Handlebars.js', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'HTML', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'Java ', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'JavaScript ', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'Jekyll', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'jQuery ', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'jQuery Mobile ', 'skillitem_id'=>'48', 'language_id'=> '1'],
            ['name'=> 'JSON ', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'LESS', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'Muse ', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'Mustache.js ', 'skillitem_id'=>'48', 'language_id'=> '1'],
            ['name'=> 'MySQL ', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'Node.js ', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'Perl ', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'Phaser ', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'PHP', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'PostgreSQL', 'skillitem_id'=>'48', 'language_id'=> '1'],
            ['name'=> 'Prototype', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'Python ', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'Ratchet ', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'React.js', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'reveal.js', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'Ruby ', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'Sass ', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'Starling', 'skillitem_id'=>'48', 'language_id'=> '1'],
            ['name'=> 'Underscore.js','skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'XHTML ', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'XML ', 'skillitem_id'=> '48', 'language_id'=> '1'],
            ['name'=> 'YAML ', 'skillitem_id'=> '48', 'language_id'=> '1'],
        ]);
        
    }
}
